### ISSUE TITLE
TypeError: Cannot call method 'getTransaction' of undefined

### ISSUE THREAD

**Issue by molinto** [taxamo/taxamo-nodejs-example#3]
After using test card, i got the following error:
TypeError: Cannot call method 'getTransaction' of undefined

**Comment by molinto** [comment]
Same error when use this code too:
https://www.taxamo.com/doc/api/nodejs/

**Comment by tlipski** [comment]
Yes, that's related to 2.1.1 being released 12 days ago and not working the same way as pre-release versions. See issue #4

**Comment by tlipski** [comment]
In the meantime, I have lowered the dependency requirement to 2.0.x
